version: "3.3"

services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: python_web
    depends_on:
      - database
    volumes:
     - ./web:/app
     - appdata:/app/data
    restart: always
    ports:
      - 5000:5000
    networks:
      - my_network

  database:
    build:
      context: ./sql
      dockerfile: ./Dockerfile
    container_name: postgresdb_container
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: always
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

volumes:
  pgdata:
  appdata: